name: dspec
description: BDD in Dart, inspired from Rspec, fork of cSpec
version: 0.1.0
repository: https://github.com/Oblivious-Oblivious/dspec

environment:
  sdk: ^3.0.2

dependencies:
  collection: ^1.17.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
